package v1

// This file contains methods that can be used by the go-restful package to generate Swagger
// documentation for the object types found in 'types.go' This file is automatically generated
// by hack/update-generated-swagger-descriptions.sh and should be run after a full build of OpenShift.
// ==== DO NOT EDIT THIS FILE MANUALLY ====

var map_Application = map[string]string{
	"":         "Application describe an Application",
	"metadata": "Standard object's metadata.",
	"spec":     "Spec defines the behavior of the Namespace.",
	"status":   "Status describes the current status of a Namespace",
}

func (Application) SwaggerDoc() map[string]string {
	return map_Application
}

var map_ApplicationList = map[string]string{
	"":         "ApplicationList describe an ApplicationList",
	"metadata": "Standard object's metadata.",
	"items":    "Items is a list of applications",
}

func (ApplicationList) SwaggerDoc() map[string]string {
	return map_ApplicationList
}

var map_ApplicationSpec = map[string]string{
	"":              "ApplicationSpec describes the attributes on a Application",
	"name":          "name defines the name of a Application",
	"items":         "items defines the resources to be labeled in a Application",
	"destoryOption": "destory defines the resources to be removed in a Application",
	"finalizers":    "Finalizers is an opaque list of values that must be empty to permanently remove object from storage",
}

func (ApplicationSpec) SwaggerDoc() map[string]string {
	return map_ApplicationSpec
}

var map_ApplicationStatus = map[string]string{
	"":      "ApplicationStatus is information about the current status of a Application",
	"phase": "phase is the current lifecycle phase of the Application",
}

func (ApplicationStatus) SwaggerDoc() map[string]string {
	return map_ApplicationStatus
}

var map_Item = map[string]string{
	"":       "Item  describe an application item",
	"kind":   "kind defines the item kind of a item in Application",
	"name":   "name defines the item name of a item in Application",
	"status": "status defines a operate to the item label",
}

func (Item) SwaggerDoc() map[string]string {
	return map_Item
}
